## basic stuff
	sudo apt-get update
	sudo apt-get update
	sudo apt-get -y upgrade
	
	sudo apt-get -y install mc zile

# sudo reboot now

## Prepare for the mounting of the volume
	 sudo mkdir /mnt/leef_data
	 sudo mount /dev/vdb /mnt/leef_data/
	 sudo chown -R ubuntu:ubuntu /mnt/leef_data
	 # sudo umount /mnt/leef_data/

## add mounting to fstab
	sudo cp /etc/fstab /etc/fstab.old
	sudo lsblk -o NAME,FSTYPE,UUID,SIZE,LABEL
	sudo zile /etc/fstab
	
	# ADD
	# UUID=a10379cf-40c6-490a-9233-1dee0552b953 /mnt/leef_data ext4 	noauto,x-systemd.automount,x-systemd.idle-timeout=300 0 0
	
	# sudo mount -a
	
## install and configure samba
	sudo apt-get -y install samba
	
## configure samba
	sudo cp -pf /etc/samba/smb.conf /etc/samba/smb.conf.bak

	sudo addgroup smbgrp
	sudo useradd leef -G smbgrp
	sudo smbpasswd -a leef
	sudo chmod -R 0770 ./leef_data
	sudo chown -R ubuntu:smbgrp ./leef_data

	sudo zile /etc/samba/smb.conf
	
The file should be as followed:

	#======================= Global Settings =======================

	[global]
		workgroup = LEEF
  	 	dns proxy = no
	
		#### Networking ####

		#### Debugging/Accounting ####

		log file = /var/log/samba/log.%m
		syslog = 0
		panic action = /usr/share/samba/panic-action %d
	
	
		####### Authentication #######

		passdb backend = tdbsam
		obey pam restrictions = yes

   		unix password sync = yes
	
   		passwd program = /usr/bin/passwd %u
   		passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
	
   		pam password change = yes
	
   		map to guest = bad user
	
		########## Domains ###########


		############ Misc ############

   		usershare allow guests = yes

	#======================= Share Definitions =======================


	[leef_data]
        comment = LEEF Data
        path = /mnt/leef_data
        browsable = yes
        writable = yes
        read only = no
        guest ok = no

Now restart samba
   	
	sudo service smbd restart
	
# Install cifs to be able to mount smb shares

	sudo apt-get install cifs-utils
	sudo mkdir /mnt/LEEF_IEU
	
# Install syncthing and configure for leef_data volume

	sudo systemctl enable syncthing@ubuntu.service
	sudo systemctl start syncthing@ubuntu.service
	echo "deb https://apt.syncthing.net/ syncthing stable" | sudo tee /etc/apt/sources.list.d/syncthing.list
	curl -s https://syncthing.net/release-key.txt | sudo apt-key add -
	printf "Package: *\nPin: origin apt.syncthing.net\nPin-Priority: 990\n" | sudo tee /etc/apt/preferences.d/syncthing
	sudo apt-get update
	sudo apt-get install syncthing	
	
	sudo systemctl enable syncthing@ubuntu.service
	sudo systemctl start syncthing@ubuntu.service

	
# **SKIP FOR NOW** setup NFS server and share
	sudo apt-get install nfs-kernel-server
	sudo mkdir /var/nfs
	sudo chown nobody:nogroup /var/nfs
	sudo ln -s /mnt/leef_data /var/nfs/leef_data
	
	
	
