# Script to setup LEEF pipeline based on Debian 10 instal

## enable ssh
  
	sudo apt-get upgrade
	sudo apt install -y openssh-server
	
## some tools
	
	sudo apt-get -y install mc

## copy id to 
	# on host machine
	# ssh-copy-id -i ~/.ssh/id_rsa.pub USER@IP

## Install R
Based on https://www.digitalocean.com/community/tutorials/how-to-install-r-on-debian-10

	sudo apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
	# add **deb http://cloud.r-project.org/bin/linux/debian buster-cran40/** to /etc/apt/sources.list
	sudo apt-get update
	sudo apt install -y -t buster-cran40 r-base
	
	# test version
	R --version
	
## Install Rstudio

	wget https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1093-amd64.deb
	sudo dpkg -i rstudio-1.3.1093-amd64.deb
	sudo apt -f -y install
		
## From dockerfile leef.base

	sudo apt-get -y --no-install-recommends install \
  		libxml2-dev \
  		libcairo2-dev \
  		libsqlite-dev \
	  	libtiff-dev \
	  	libssh2-1-dev \
 	 	libssl-dev \
		libpq-dev \
  		libcairo2-dev \
   		libxt-dev \
    	openjdk-11-jdk-headless
	
	mkdir -p ~/R/x86_64-pc-linux-gnu-library/4.0
	
    R -e 'install.packages(c('littler', 'docopt'))'
    sudo ln -s /home/parallels/R/x86_64-pc-linux-gnu-library/4.0/littler/bin/r /usr/local/bin/
    
    R -e 'install.packages('BiocManager')'
    R -e 'BiocManager::install('flowCore')'
    
    R -e "install.packages( 
    	c( 
 	    	'ps', 
    		'utf8',  
    		'processx',  
    		'mvtnorm', 
    		'pillar',  
    		'pkgconfig',  
    		'purrr',  
    		'sys', \
    		'callr',  
    		'prettyunits',  
    		'backports',  
    		'data.table',  
    		'circular',  
    		'settings',  
    		'generics',  
    		'lifecycle',  
    		'tibble',  
    		'tidyselect',  
    		'vctrs',  
    		'hms',  
    		'clipr', 
    		'askpass',  
    		'assertthat',  
    		'fansi',  
    		'desc', 
    		'pkgbuild', 
    		'rprojroot', 
    		'rstudioapi',
    		'dplyr',
    		'readr',
    		'tiff', 
    		'openssl',
    		'cli',
    		'crayon', 
    		'ellipsis',
    		'pkgload',
    		'praise',
    		'R6',
    		'withr',
    		'R.oo',
    		'R.methodsS3',
    		'testthat',
    		'R.utils',
    		'shiny',
    		'drat'
    	) )"
    	
## From dockerfile leef

	mkdir -p /home/parallels/LEEF/tools
	mkdir -p /home/parallels/LEEF/000.NewData
    mkdir -p /home/parallels/LEEF/0.raw.data
    mkdir -p /home/parallels/LEEF/1.pre-processed.data 
    mkdir -p /home/parallels/LEEF/2.extracted.data 
    mkdir -p /home/parallels/LEEF/3.archived.data 
    mkdir -p /home/parallels/LEEF/9.backend
    
	cd /home/parallels/LEEF/tools
	
	wget http://downloads.openmicroscopy.org/latest/bio-formats5.6/artifacts/bftools.zip
    unzip ./bftools.zip
    rm ./bftools.zip  
   
    wget https://downloads.imagej.net/fiji/archive/20191027-2045/fiji-linux64.zip
    unzip ./fiji-linux64.zip
    rm ./fiji-linux64.zip
	
    wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
	tar -xf ffmpeg-release-amd64-static.tar.xz --wildcards --strip=1 */ffmpeg
	rm ./ffmpeg-release-amd64-static.tar.xz
	
	wget https://github.com/LEEF-UZH/docker/raw/master/leef/tools/ParticleLinker.jar
	
	R -e "drat::addRepo('LEEF-UZH'); install.packages(c('LEEF.archive.default', 'LEEF'))"
	
	