---
title: "Pipeline"
author: "Rainer M Krug"
format: 
  html:
    toc: true
    toc-location: left
    toc-depth: 5
    code-fold: true
    embed-resources: true
---

```{r}
#| label: setup
#| echo: false

# library(plantuml)
```

# LEEF Data Proccerssing 

## Pipeline

### Raw data  / measured Data
The Raw data is the data as recorded during the measurements of different properties of the system. The format is determined by the manufacturer of the machines and in some cases ion a proprietary format. This data is deleted after the procesessing via the pipeline and the data cleanining steps.

The following techniques are used to measure properties of the system:

- **Bemovi**: Two different sets of videos were recorded at 16 and 25 times magnification to determine densities and traits of ...
- **Flowcam**: record traits and densities of ...
- **Flowcytometer**:  record traits and densities of bacteria
- **O~2~ Measurements**: record O~2~ concentration at two different depths in the microcosm
- **Manual Count**: Manually count ...

### Pre-Processor
During the preprocessing step the raw data is in a lossless conversions and compressions (images and videos) converted into open formats. The resulting data is archive ready and has the same information content as the original raw data. This data is archived on Zenodo and has the (DOI)[LINK].

- **Bemovi**: the videos, recorded in `.cxd` format, are converted to lossless compressed `.avi` format and the metadata contained in the original videos is extracted into a text file
- **Flowcam**: The data is just copied as it is already in an open format
- **Flowcytometer**: The data is just copied as it is already in an open format
- **O~2~ Measurements**: The data is just copied as it is already in an open format
- **Manual Count**: The data is just copied as it is already in an open format

### Extractor
Here the information is extracted which is needed for the actual analysis. The extracted data is archived on Zenodo and has the (DOI)[LINK].

- Bemovi  
  
  4 different analysis are done to extract the data for the analysis with the parameter for each extraction in a `.yml` file 

   - **Magnification 16** (`bemovi_extract.mag.16.yml`)
   - **Magnification 25** (`bemovi_extract.mag.25.yml`)
   - **Magnification 25 uncropped** (`bemovi_extract.mag.25.non_cropped.yml`)
   - **Magnification 25 uncropped** (`bemovi_extract.mag.25.cropped.yml`)  
  
  Which differ in the parameters of the analysis.
From each of these sets, 
68.50 + 117.60 +

#### Flowcam
#### Flowcytometer
#### O~2~ Measurements
#### Manual Count


### Add to RRD database
The Extracted data is added to the  RRD (Research Ready Database). The RRD contains all the data needed for the actual analysis done in the leef project. It is important to note, that the RRD generated via the pipeline runs, has to be considered as preliminary, as classifiers were changed and data cleaning done after the finalisation of the experiment. The final RRD (same structure as the one generated by the pipeline) is generated as described in section [Final data cleaning and creation of final RRD](#LINK_TO_SECTION)

## Final data cleaning and creation of final RRD
Final data cleaning is done based on the extracted data. The data is re-classified, species, movies, and duplicates removed and the water chemistry measurements are de-trended. We give here a short outline of the processes, while the whole data cleaning code and description in the [Final Data Cleaning and reclassification report](LINK).
  As a last step, the species names and column names were changed to a consistent naming suitable for analysis and plotting.
  
### Bemovi
For the video recordings for bemovi data, the steps were:

- reclassification
- removal of certain species / particle types
- removal of videos with moving background (camera shake during recording)
- removal of duplicates
- calculation of biomass

### Flowcam
For the flowcam data, the steps were:

- reclassification
- use of special classifier for one bottle after contamination
- removal of certain species / particle types
- calculation of biomass

### Flowcytometer
For the flowcytometer data, the steps were:

- re-gating
- use of special gates for certain samples done with different flowcytometer due to repair of original Flowcytometer
- selection of only bacteria
- setting of identification level for Stau1 to 0.95 in contrast to 0.9 for other species
- calculation of biomass


### O~2~ Measurements
No cleaning needed.

### Manual Count
No cleaning needed.

### Water Chemistry
Removal of the linear trend in the IC, OC, TOC, TN measurements.


