default:
  maintainer:
    name: Max Mustermann
    email: Max@musterfabrik.example
  description: This is my fantastic repo
               with lots of data.

Master:
  doi: FALSE
  tts: TRUE
  data:
    backend:
      driver: "RSQLite::SQLite()"
      dbpath: NULL
      dbname: "rawData.sqlite"

Main:
  doi: FALSE
  tts: TRUE
  data:
    backend:
      dryver: "RMySQL::MySQL()"
      Database: "[database name]"
      dots: NULL

Public:
  doi: TRUE
  tts: TRUE
  data:
    backend:
      csv:
        folder: rawData

