default:
  maintainer:
    name: Rainer M. Krug
    email: Rainer@uzh.ch
  description: LEEF Data from an long term experiment.
               Some more detaled info has to follow.
  archive_compression: tar
  tts_info:
    name: Rainer M Krug
    email: Rainer.Krug@uzh.ch
    comment: testdata
    archivename: To Be Set

Master:
  doi: FALSE
  tts: TRUE
  data:
    backend:
      driver: "RSQLite::SQLite()"
      dbpath: NULL
      dbname: "LEEFData.sqlite"

Main:
  doi: FALSE
  tts: TRUE
  data:
    backend:
      dryver: "RMySQL::MySQL()"
      Database: "[database name]"
      dots: NULL

Public:
  doi: TRUE
  tts: TRUE
  data:
    backend:
      csv:
        folder: rawData

