default:
  configname: LEEFData
  description: LEEF Data from an long term experiment.
               Some more detaled info has to follow.
  maintainer:
    name: Rainer M. Krug
    email: Rainer@uzh.ch
  archive_compression: tar
  tts: TRUE
  tts_info:
    name: Rainer M Krug
    email: Rainer.Krug@uzh.ch
    comment: testdata
    archivename: To Be Set
  doi: FALSE
  data:
    backend:
      driver: "RSQLite::SQLite()"
      dbpath: NULL
      dbname: "LEEFData.sqlite"
