## General info
##
config_name: LEEFData
description: LEEF Data from an long term experiment.
             Some more detaled info has to follow.
maintainer: Rainer M. Krug <Rainer@uzh.ch>



## Directorie for the processing.
## The folder structure in this directory
## has to be one folder for each measurement type.
##
directories:
  raw:
  pre_processed:
  extracted:
  archive:

## queues containing functions.
## These should be left blank, as they will be owerwritten.
##
queues:
  pre_processors:
  extractors:
  archivers:
  additors:

## R library for packages installed by initilize()
## leave blank for temporary location
#
library_path:

## Packages which contain the pre_processors, extractors, additors, ...
##
measurement_packages:
  LEEF.measurement.bemovi:
    name: LEEF.measurement.bemovi
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.bemovi', upgrade = "never")
    RegisterCommand: LEEF.measurement.bemovi::tools_path(tools_path = '.'); LEEF.measurement.bemovi::register()
  LEEF.measurement.flocam:
    name: LEEF.measurement.flowcam
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.flowcam', upgrade = "never")
    RegisterCommand: LEEF.measurement.flowcam::register()
  LEEF.measurement.flowcytometer:
    name: LEEF.measurement.flowcytometer
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.flowcytometer', upgrade = "never")
    RegisterCommand: LEEF.measurement.flowcytometer::register()
  LEEF.measurement.incubatortemp:
    name: LEEF.measurement.incubatortemp
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.incubatortemp', upgrade = "never")
    RegisterCommand: LEEF.measurement.incubatortemp::register()
  LEEF.measurement.manualcount:
    name: LEEF.measurement.manualcount
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.manualcount', upgrade = "never")
    RegisterCommand: LEEF.measurement.manualcount::register()
  LEEF.measurement.respirometer:
    name: LEEF.measurement.respirometer
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.respirometer', upgrade = "never")
    RegisterCommand: LEEF.measurement.respirometer::register()
  LEEF.measurement.toc:
    name: LEEF.measurement.toc
    InstallCommand: remotes::install_github('rkrug/LEEF.measurement.toc', upgrade = "never")
    RegisterCommand: LEEF.measurement.toc::register()

# archival_packages:
#   LEEF.archive.default:
#    name: LEEF.archive.default
#    InstallCommand: remotes::install_github('rkrug/LEEF.archive.default', upgrade = "never")
#    RegisterCommand: RegisterCommand:LEEF.archive.default::register()

archive:
  name: LEEF
  compression: tar

tts: TRUE
tts_info:
  name: Rainer M Krug
  email: Rainer.Krug@uzh.ch
  comment: testdata
  archivename: To Be Set

doi: FALSE

database:
  driver: 'RSQLite::SQLite()'
  dbpath:
  dbname: 'LEEFData.sqlite'
