# General info
# --------------------------------------------------------------------
# General info regarding the processing


name: LEEF-2
description: LEEF-2 Data from an long term experiment.
             Some more detaled info has to follow.
maintainer: Rainer M. Krug <Rainer@uzh.ch>


# --------------------------------------------------------------------
# Directorie for the processing
# --------------------------------------------------------------------
## The folder structure in this directory
## has to be one folder for each measurement type.
##


directories:
  raw: "0.raw.data"
  pre_processed: "1.pre-processed.data"
  extracted: "2.extracted.data"
  archive: "3.archived.data"
  backend: "9.backend"
  tools: "tools"


# --------------------------------------------------------------------
# Packages which contain the pre_processors, extractors, additors, ...
# --------------------------------------------------------------------
# These will be installed using the `InstallCommand` and registered
# in the queue using the `RegisterCommand`.
# The RegisterCommand` can also contain additional customizations needed by the processors.


measurement_packages:
  LEEF.2.measurement.bemovi:
    name: LEEF.2.measurement.bemovi
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.measurement.bemovi')
    RegisterCommand: LEEF.2.measurement.bemovi::tools_path(tools_path = '.'); LEEF.2.measurement.bemovi::register()
  LEEF.2.measurement.conductivity:
    name: LEEF.2.measurement.conductivity
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.measurement.conductivity')
    RegisterCommand: LEEF.2.measurement.conductivity::register()
  LEEF.2.measurement.flocam:
    name: LEEF.2.measurement.flowcam
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages(('LEEF.2.measurement.flowcam')
    RegisterCommand: LEEF.2.measurement.flowcam::register()
  LEEF.2.measurement.flowcytometer:
    name: LEEF.2.measurement.flowcytometer
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.measurement.flowcytometer')
    RegisterCommand: LEEF.2.measurement.flowcytometer::register()
  LEEF.2.measurement.manualcount:
    name: LEEF.2.measurement.manualcount
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.measurement.manualcount')
    RegisterCommand: LEEF.2.measurement.manualcount::register()
  LEEF.2.measurement.o2meter:
    name: LEEF.2.measurement.o2meter
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.measurement.o2meter')
    RegisterCommand: LEEF.2.measurement.o2meter::register()



# --------------------------------------------------------------------
# archival_packages
# --------------------------------------------------------------------
# These will be installed using the `InstallCommand` and registered
# in the queue using the `RegisterCommand`.
# The RegisterCommand` can also contain additional customizations needed by the processors.
# Additional values are archival package specific.


archive_packages:
  LEEF.2.archive.default:
    name: LEEF.2.archive.default
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.archive.default')
    RegisterCommand: LEEF.2.archive.default::register(compression = "none")

# --------------------------------------------------------------------
# backend packages ()
# --------------------------------------------------------------------
# These will be installed using the `InstallCommand` and registered
# in the queue using the `RegisterCommand`.
# The RegisterCommand` can also contain additional customizations needed by the processors.
# Additional values are arcival package specific.

## NOT IMPLEMENTED YET
## SOME MORE THOUGHT NEEDED HERE!


backend_packages:
  LEEF.2.backend.csv:
    name: LEEF.2.backend.csv
    InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.backend.csv')
    RegisterCommand: LEEF.2.backend.csv::register()
  # LEEF.2.backend.sqlite:
  #   name: LEEF.2.backend.sqlite
  #   InstallCommand: drat::addRepo('LEEF-UZH'); install.packages('LEEF.2.backend.sqlite')
  #   RegisterCommand: LEEF.2.backend.sqlite::register()
  #   dbpath:
  #   dbname: 'LEEFData.sqlite'


# --------------------------------------------------------------------
# Trusted Time Stamps
# --------------------------------------------------------------------
## NOT IMPLEMENTED YET
## SOME MORE THOUGHT NEEDED HERE!


tts:
  create: TRUE
  api_key: PRIVATE
  notification:
    notification_type: 0
    target: tsg@LEEF-UZH.ch


# --------------------------------------------------------------------
# DOI
# --------------------------------------------------------------------
## NOT IMPLEMENTED YET


doi: FALSE

# --------------------------------------------------------------------
# queues containing functions
# --------------------------------------------------------------------
## These should be left blank, as they WILL be owerwritten.


queues:
  pre_processors:
  extractors:
  archivers:
  additors:

