nd_names <- c("X", "Particle.ID", "Area..ABD.", "Area..Filled.", "Aspect.Ratio",
              "Average.Blue", "Average.Green", "Average.Red", "Calibration.Factor",
              "Calibration.Image", "Camera", "Capture.X", "Capture.Y", "Ch1.Area",
              "Ch1.Peak", "Ch1.Width", "Ch2.Area", "Ch2.Peak", "Ch2.Width",
              "Ch2.Ch1.Ratio", "Circle.Fit", "Circularity", "Circularity..Hu.",
              "Compactness", "Convex.Perimeter", "Convexity", "Date", "Diameter..ABD.",
              "Diameter..ESD.", "Edge.Gradient", "Elongation", "Feret.Angle.Max",
              "Feret.Angle.Min", "Fiber.Curl", "Fiber.Straightness", "Filter.Score",
              "Geodesic.Aspect.Ratio", "Geodesic.Length", "Geodesic.Thickness",
              "Image.File", "Image.Height", "Image.Width", "Image.X", "Image.Y",
              "Intensity", "Length", "Particles.Per.Chain", "Perimeter", "Ratio.Blue.Green",
              "Ratio.Red.Blue", "Ratio.Red.Green", "Roughness", "Scatter.Area",
              "Scatter.Peak", "Scatter.Width", "Sigma.Intensity", "Source.Image",
              "Sum.Intensity", "Symmetry", "Time", "Timestamp", "Transparency",
              "Volume..ABD.", "Volume..ESD.", "Width")
